version: '3.8'

services:
  node-dev-env:
    build: .
    command: npm start
    ports:
      - 5000:5000
    volumes:
      - ./reaktor-pre-assignment:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: node-dev-env

volumes:
  node_modules:
