version: '3.8'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
  redis:
    image: redis
    ports:
       - 6379:6379
  backend:
    build:
      ./backend
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      REDIS_HOST: redis
  frontend:
    build:
      ./frontend
    ports:
      - 5000:5000
