version: '3.8'

services:
  redis:
    image: redis
    ports:
       - 6379:6379
  backend:
    build:
      ./backend
    ports:
      - 8080:8080
  frontend:
    build:
      ./frontend
    ports:
      - 5000:5000
